import type { Metadata } from "next";
import "./globals.css";
import axios from "axios";
import Navbar from "@/components/Navbar";

axios.defaults.baseURL = process.env.BASE_URL;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <div className="">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
